from typing import List, Dict, TypedDict, Optional

class VideoGenerationState(TypedDict):
    """
    Represents the state of a single video generation job.
    """
    prompt: str
    
    # The script text generated by Gemini
    script: Optional[str]
    
    # The list of scenes
    storyboard: List[Dict]
    
    # Dictionary holding URLs for video clips AND the voiceover audio
    asset_urls: Dict[str, str]
    
    final_video_url: Optional[str]
    error_message: Optional[str]